In [ ]:
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
import collections

In [ ]:
import os
import json

In [ ]:
f = open("/content/drive/MyDrive/EE8101_Deep_Learning/Model_try/wordDictionary.json", "w")
json.dump(dct, f)
f.close()

In [ ]:
dct2

{'a': 0,
 'abdomen': 1,
 'able': 2,
 'about': 3,
 'above': 4,
 'accent': 5,
 'accept': 6,
 'accident': 7,
 'accomplish': 8,
 'accountant': 9,
 'across': 10,
 'action': 11,
 'active': 12,
 'activity': 13,
 'actor': 14,
 'add': 15,
 'address': 16,
 'adjective': 17,
 'adjust': 18,
 'admit': 19,
 'adopt': 20,
 'adult': 21,
 'advanced': 22,
 'advantage': 23,
 'adverb': 24,
 'affect': 25,
 'afraid': 26,
 'africa': 27,
 'after': 28,
 'afternoon': 29,
 'again': 30,
 'against': 31,
 'age': 32,
 'agenda': 33,
 'ago': 34,
 'agree': 35,
 'ahead': 36,
 'aid': 37,
 'aim': 38,
 'airplane': 39,
 'alarm': 40,
 'alcohol': 41,
 'algebra': 42,
 'all': 43,
 'all day': 44,
 'allergy': 45,
 'allow': 46,
 'almost': 47,
 'alone': 48,
 'a lot': 49,
 'alphabet': 50,
 'already': 51,
 'also': 52,
 'always': 53,
 'amazing': 54,
 'america': 55,
 'analyze': 56,
 'anatomy': 57,
 'and': 58,
 'angel': 59,
 'angle': 60,
 'angry': 61,
 'animal': 62,
 'anniversary': 63,
 'announce': 64,
 'annoy': 65,
 'another': 66,
 'answ

In [ ]:
# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyper-parameters
input_size = 2 * 21 * 3
sequence_length = 233
hidden_size = 128
hidden_size2 = 64
num_classes = 1971
num_layers = 2
nonlinearity = 'tanh'
num_epochs = 500
batch_size = 512
learning_rate = 0.001

In [ ]:
labels = [i[:-4].split('_')[1] for i in sorted(os.listdir('/content/drive/MyDrive/EE8101_Deep_Learning/NaN_to_Zero_Arrays'))]

In [ ]:
labels = [i[:-4].split('_')[1] for i in sorted(os.listdir('/content/drive/MyDrive/EE8101_Deep_Learning/NaN_to_Zero_Arrays'))]
label_num = [0]
dct = {0: 'a'}
dct2 = {'a': 0}
labl = 0
for i in range(1, 17875):
    if labels[i] not in dct2:
        labl += 1
        dct2[labels[i]] = labl
        print(labels[i])
    label_num.append(dct2[labels[i]])
    dct[dct2[labels[i]]] = labels[i]
y = torch.tensor(label_num, dtype = torch.int32)

abdomen
able
about
above
accent
accept
accident
accomplish
accountant
across
action
active
activity
actor
add
address
adjective
adjust
admit
adopt
adult
advanced
advantage
adverb
affect
afraid
africa
after
afternoon
again
against
age
agenda
ago
agree
ahead
aid
aim
airplane
alarm
alcohol
algebra
all
all day
allergy
allow
almost
alone
a lot
alphabet
already
also
always
amazing
america
analyze
anatomy
and
angel
angle
angry
animal
anniversary
announce
annoy
another
answer
any
anyway
apart
apartment
apostrophe
appear
appetite
apple
appointment
appreciate
approach
appropriate
approve
april
archery
area
argue
arizona
arm
army
around
arrest
arrive
arrogant
art
article
artist
asia
ask
asl
assist
assistant
assume
attend
attention
attitude
attorney
attract
auction
audience
audiologist
audiology
august
aunt
australia
austria
author
authority
autumn
available
average
avoid
awake
award
aware
away
awful
awkward
b
baby
babysitter
background
back
backpack
bacon
bad
bake
balance
bald
ball
balloon
banana

In [ ]:
X_train = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/Model_try/training_arrays.npy')
X_test = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/Model_try/testing_arrays.npy')
frame_num_train = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/Model_try/training_frame_num.npy')
frame_num_test = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/Model_try/testing_frame_num.npy')
y_train = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/Model_try/training_labels.npy')
y_test = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/Model_try/testing_labels.npy')

In [ ]:
X_train.shape

(14896, 233, 126)

In [ ]:
X_train[0].sum(1)

array([ 0.        ,  0.        ,  0.        , 23.42533903, 23.11023066,
       21.2307034 , 21.9729319 , 36.06817085, 56.90787542, 19.04238875,
       41.28469116, 40.96199688, 41.45766264, 41.18082742, 41.00101845,
       41.07685537, 41.03398366, 42.06064535, 43.8222885 , 22.10914673,
       22.8937499 , 28.89483696,  0.        ,  0.        , 28.21367225,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [ ]:
(X_train[0].sum(1) > 0).argmax()

3

In [ ]:
len(X_train[0]) - (X_train[0].sum(1)[::-1] > 0).argmax()

25

In [ ]:
X_train[0].sum(1)[3:25]

array([23.42533903, 23.11023066, 21.2307034 , 21.9729319 , 36.06817085,
       56.90787542, 19.04238875, 41.28469116, 40.96199688, 41.45766264,
       41.18082742, 41.00101845, 41.07685537, 41.03398366, 42.06064535,
       43.8222885 , 22.10914673, 22.8937499 , 28.89483696,  0.        ,
        0.        , 28.21367225])

In [ ]:
train_dataset = [(X_train[i], y_train[i], frame_num_train[i]) for i in range(len(X_train))]
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

test_dataset = [(X_test[i], y_test[i], frame_num_test[i]) for i in range(len(X_test))]
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size = batch_size, shuffle = False)

In [ ]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(RNN, self).__init__()
        self.gru = nn.GRU(input_size = input_size, hidden_size = hidden_size, num_layers = 3, batch_first = True)
        self.foc = nn.Linear((hidden_size), (num_classes))

    def forward(self, x):
        x, h_n = self.gru(x)
        output = self.foc(h_n[-1])
        return output

In [ ]:
model = RNN(input_size, hidden_size, num_layers, num_classes).double().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [ ]:
optimizer = torch.optim.Adam(model.parameters(), lr = 0.0001)

In [ ]:
losses = []
print_loss_every = 20
print_acc_every = 20

for epoch in range(200):
    for i, (videos, labels, framenums) in enumerate(train_loader):
        information = torch.nn.utils.rnn.pack_padded_sequence(videos, framenums, batch_first = True, enforce_sorted = False).to(device)
        # origin shape: [4, 3, 32, 32] = 4, 3, 1024
        # input_layer: 3 input channels, 6 output channels, 5 kernel size
        labels = labels.to(torch.long).to(device)

        # Forward pass
        outputs = model(information)
        loss = criterion(outputs, labels)
        losses.append(loss)

        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if (i+1) % print_loss_every == 0:
          print (f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}], Loss: {loss.item():.4f}')

    with torch.no_grad():
        total = 0
        total_correct = 0
        for i, (videos, labels, framenums) in enumerate(test_loader):
            information = torch.nn.utils.rnn.pack_padded_sequence(videos, framenums, batch_first = True, enforce_sorted = False).to(device)
            # origin shape: [4, 3, 32, 32] = 4, 3, 1024
            # input_layer: 3 input channels, 6 output channels, 5 kernel size
            labels = labels.to(torch.long).to(device)

            # Forward pass
            outputs = model(information)
            outputs = torch.argmax(outputs, dim=-1)

            # Backward and optimize
            total += len(outputs)
            total_correct += (outputs == labels).sum().item()

        print(f"Accuracy: {total_correct / total * 100:.2f}")

Epoch [1/500], Step [20], Loss: 7.5913
Accuracy: 0.03
Epoch [2/500], Step [20], Loss: 7.5775
Accuracy: 0.03
Epoch [3/500], Step [20], Loss: 7.5783
Accuracy: 0.10
Epoch [4/500], Step [20], Loss: 7.5517
Accuracy: 0.00
Epoch [5/500], Step [20], Loss: 7.5343
Accuracy: 0.10
Epoch [6/500], Step [20], Loss: 7.4660
Accuracy: 0.13
Epoch [7/500], Step [20], Loss: 7.3972
Accuracy: 0.17
Epoch [8/500], Step [20], Loss: 7.3084
Accuracy: 0.17
Epoch [9/500], Step [20], Loss: 7.2656
Accuracy: 0.17
Epoch [10/500], Step [20], Loss: 7.2194
Accuracy: 0.17
Epoch [11/500], Step [20], Loss: 7.1083
Accuracy: 0.17
Epoch [12/500], Step [20], Loss: 7.1414
Accuracy: 0.17
Epoch [13/500], Step [20], Loss: 7.1401
Accuracy: 0.17
Epoch [14/500], Step [20], Loss: 7.0896
Accuracy: 0.13
Epoch [15/500], Step [20], Loss: 7.0412
Accuracy: 0.13
Epoch [16/500], Step [20], Loss: 7.0578
Accuracy: 0.13
Epoch [17/500], Step [20], Loss: 6.9992
Accuracy: 0.17
Epoch [18/500], Step [20], Loss: 7.0428
Accuracy: 0.13
Epoch [19/500], Ste

In [ ]:
torch.save(model.state_dict(), '/content/drive/MyDrive/EE8101_Deep_Learning/model_3percent2.pt')

In [ ]:
videos, labels = iter(train_loader).next()

In [ ]:
padded_sequences = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/Model_try/raw_flat.npy')

In [ ]:
frame_nums = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/Model_try/Frame_num.npy').astype(int)
np.max(frame_nums)

233

In [ ]:
X_train, X_test, y_train, y_test, frame_num_train, frame_num_test = train_test_split(padded_sequences, y, frame_nums, test_size = 17875 // 6, random_state=2020)

In [ ]:
np.save('/content/drive/MyDrive/EE8101_Deep_Learning/training_arrays', X_train)
np.save('/content/drive/MyDrive/EE8101_Deep_Learning/training_labels', y_train)
np.save('/content/drive/MyDrive/EE8101_Deep_Learning/training_frame_num', frame_num_train)
np.save('/content/drive/MyDrive/EE8101_Deep_Learning/testing_arrays', X_test)
np.save('/content/drive/MyDrive/EE8101_Deep_Learning/testing_labels', y_test)
np.save('/content/drive/MyDrive/EE8101_Deep_Learning/testing_frame_num', frame_num_test)

In [ ]:
dataset = [(padded_sequences[i], y[i], frame_nums[i]) for i in range(17875)]

In [ ]:
sorted(dataset, key = lambda x: x[1])

[(array([[ 2.39173457e-01,  6.72451258e-01, -3.21984298e-05, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 2.39364684e-01,  6.72565877e-01, -3.05471331e-05, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 2.39452019e-01,  6.72343254e-01, -3.30108705e-05, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         ...,
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]),
  tensor(0, dtype=torch.int32),
  23),
 (array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
   

In [ ]:
vid_nums = {}
count_y_train = collections.Counter(y_train)
count_y_test = collections.Counter(y_test)
for i in range(1971):
    if (count_y_train[i] + count_y_test[i]) not in vid_nums:
        vid_nums[count_y_train[i] + count_y_test[i]] = 1
    else:
        vid_nums[count_y_train[i] + count_y_test[i]] += 1 
    print(f'{i}: {count_y_train[i]} / {count_y_train[i] + count_y_test[i]}')

0: 4 / 6
1: 7 / 7
2: 4 / 7
3: 12 / 14
4: 7 / 8
5: 1 / 1
6: 9 / 11
7: 15 / 17
8: 6 / 8
9: 5 / 7
10: 5 / 9
11: 7 / 7
12: 5 / 8
13: 6 / 7
14: 9 / 9
15: 8 / 10
16: 6 / 7
17: 1 / 1
18: 1 / 1
19: 1 / 1
20: 5 / 7
21: 10 / 11
22: 1 / 2
23: 8 / 8
24: 1 / 1
25: 6 / 7
26: 7 / 8
27: 13 / 15
28: 10 / 11
29: 11 / 11
30: 11 / 14
31: 5 / 7
32: 10 / 12
33: 4 / 7
34: 9 / 11
35: 7 / 8
36: 6 / 7
37: 1 / 1
38: 4 / 7
39: 10 / 10
40: 7 / 9
41: 7 / 7
42: 7 / 7
43: 14 / 19
44: 5 / 7
45: 9 / 9
46: 9 / 11
47: 7 / 9
48: 11 / 12
49: 6 / 8
50: 6 / 8
51: 10 / 10
52: 10 / 10
53: 12 / 13
54: 7 / 8
55: 9 / 11
56: 9 / 10
57: 0 / 1
58: 8 / 10
59: 9 / 11
60: 5 / 7
61: 10 / 11
62: 8 / 12
63: 8 / 8
64: 8 / 9
65: 0 / 1
66: 7 / 8
67: 9 / 11
68: 9 / 11
69: 1 / 2
70: 7 / 7
71: 8 / 9
72: 6 / 7
73: 8 / 10
74: 5 / 7
75: 14 / 17
76: 13 / 13
77: 7 / 8
78: 1 / 1
79: 7 / 8
80: 13 / 13
81: 7 / 8
82: 7 / 7
83: 6 / 9
84: 11 / 13
85: 0 / 1
86: 9 / 10
87: 6 / 10
88: 6 / 7
89: 9 / 10
90: 7 / 14
91: 8 / 9
92: 10 / 11
93: 7 / 7
94: 5 / 7
95: 

In [ ]:
vid_nums

{1: 109,
 2: 52,
 3: 11,
 4: 3,
 5: 13,
 6: 201,
 7: 259,
 8: 260,
 9: 247,
 10: 194,
 11: 182,
 12: 123,
 13: 101,
 14: 65,
 15: 40,
 16: 39,
 17: 21,
 18: 17,
 19: 16,
 20: 7,
 21: 5,
 22: 2,
 24: 1,
 25: 1,
 28: 1,
 32: 1}

In [ ]:
sorted(labels)

['a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a lot',
 'a lot',
 'a lot',
 'a lot',
 'a lot',
 'a lot',
 'a lot',
 'a lot',
 'abdomen',
 'abdomen',
 'abdomen',
 'abdomen',
 'abdomen',
 'abdomen',
 'abdomen',
 'able',
 'able',
 'able',
 'able',
 'able',
 'able',
 'able',
 'about',
 'about',
 'about',
 'about',
 'about',
 'about',
 'about',
 'about',
 'about',
 'about',
 'about',
 'about',
 'about',
 'about',
 'above',
 'above',
 'above',
 'above',
 'above',
 'above',
 'above',
 'above',
 'accent',
 'accept',
 'accept',
 'accept',
 'accept',
 'accept',
 'accept',
 'accept',
 'accept',
 'accept',
 'accept',
 'accept',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accident',
 'accomplish',
 'accomplish',
 'accomplish',
 'accomplish',
 'accomplish',
 'accomplish',
 'accomplish',
 'accomplish',
 'accountant',
 'accountant',
 'accountant',

In [ ]:
videos.dtype

torch.float64

In [ ]:
torch.double

torch.float64

In [ ]:
[1] * 10 ** 10

In [ ]:
len(dct)

1971

In [ ]:
model = torch.load('/content/drive/MyDrive/EE8101_Deep_Learning/Model_try/model_3percent.pt')

AttributeError: ignored

In [ ]:
np.save('/content/drive/MyDrive/EE8101_Deep_Learning/testing_labels.npy', y_test)

In [ ]:
arr2 = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/training_labels.npy')

In [ ]:
arr2[0]

658

In [ ]:
arr[3]

array([[ 2.42430046e-01,  6.80513263e-01, -7.53411514e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.38606423e-01,  6.67012036e-01, -7.37481387e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.38849625e-01,  6.66965187e-01, -7.12456458e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [ ]:
dataiter = train_loader))

In [ ]:
X_train, X_test = torch.from_numpy(X_train), torch.from_numpy(X_test)

In [ ]:
train_loader = torch.utils.data.DataLoader(X_train, batch_size = 1024, shuffle = True)


torch.Size([14896, 233, 126])

In [ ]:
model = torch.nn.RNN(input_size = input_size, hidden_size = hidden_size, num_layers = num_layers, nonlinearity = nonlinearity)

In [ ]:
lst = os.listdir('/content/drive/MyDrive/EE8101_Deep_Learning/NaN_to_Zero_Arrays')

In [ ]:
lst = sorted(lst)

In [ ]:
lst

['00295_a.npy',
 '00333_abdomen.npy',
 '00335_abdomen.npy',
 '00336_abdomen.npy',
 '00337_abdomen.npy',
 '00338_abdomen.npy',
 '00339_abdomen.npy',
 '00341_abdomen.npy',
 '00374_able.npy',
 '00376_able.npy',
 '00377_able.npy',
 '00378_able.npy',
 '00381_able.npy',
 '00382_able.npy',
 '00384_able.npy',
 '00412_about.npy',
 '00414_about.npy',
 '00415_about.npy',
 '00416_about.npy',
 '00419_about.npy',
 '00421_about.npy',
 '00422_about.npy',
 '00423_about.npy',
 '00424_about.npy',
 '00426_about.npy',
 '00429_above.npy',
 '00430_above.npy',
 '00431_above.npy',
 '00432_above.npy',
 '00433_above.npy',
 '00435_above.npy',
 '00581_accent.npy',
 '00588_accept.npy',
 '00592_accept.npy',
 '00593_accept.npy',
 '00594_accept.npy',
 '00597_accept.npy',
 '00598_accept.npy',
 '00599_accept.npy',
 '00600_accept.npy',
 '00601_accept.npy',
 '00603_accept.npy',
 '00618_accident.npy',
 '00623_accident.npy',
 '00624_accident.npy',
 '00625_accident.npy',
 '00626_accident.npy',
 '00627_accident.npy',
 '00628_

In [ ]:
xx = []
yy = []

In [ ]:
arr = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/NaN_to_Zero_Arrays/' + lst[0])

In [ ]:
np.resize(arr, (23, 2 * 21 * 3))[5]

array([ 2.38675401e-01,  6.72467947e-01, -2.83472691e-05,  2.67727405e-01,
        6.40496373e-01, -1.34471003e-02,  2.88694978e-01,  5.92388988e-01,
       -2.29447354e-02,  2.97036827e-01,  5.55968046e-01, -3.53258438e-02,
        2.93872327e-01,  5.27686656e-01, -4.45128083e-02,  2.65941203e-01,
        5.59725642e-01, -1.98728405e-02,  2.73324937e-01,  5.25863707e-01,
       -4.89713028e-02,  2.73967862e-01,  5.66880405e-01, -5.43906763e-02,
        2.70994246e-01,  5.95913172e-01, -5.07622547e-02,  2.46374473e-01,
        5.63132405e-01, -2.71788482e-02,  2.50483215e-01,  5.29888690e-01,
       -6.69134855e-02,  2.54202873e-01,  5.77606559e-01, -7.11878464e-02,
        2.52018899e-01,  6.06927633e-01, -6.41074851e-02,  2.25350142e-01,
        5.70919633e-01, -3.77819277e-02,  2.29911387e-01,  5.38276613e-01,
       -7.09495023e-02,  2.36955583e-01,  5.80903351e-01, -6.83231726e-02,
        2.35669553e-01,  6.07181191e-01, -6.03439547e-02,  2.02982575e-01,
        5.83927035e-01, -

In [ ]:
arr[5]

array([[[ 2.38675401e-01,  6.72467947e-01, -2.83472691e-05],
        [ 2.67727405e-01,  6.40496373e-01, -1.34471003e-02],
        [ 2.88694978e-01,  5.92388988e-01, -2.29447354e-02],
        [ 2.97036827e-01,  5.55968046e-01, -3.53258438e-02],
        [ 2.93872327e-01,  5.27686656e-01, -4.45128083e-02],
        [ 2.65941203e-01,  5.59725642e-01, -1.98728405e-02],
        [ 2.73324937e-01,  5.25863707e-01, -4.89713028e-02],
        [ 2.73967862e-01,  5.66880405e-01, -5.43906763e-02],
        [ 2.70994246e-01,  5.95913172e-01, -5.07622547e-02],
        [ 2.46374473e-01,  5.63132405e-01, -2.71788482e-02],
        [ 2.50483215e-01,  5.29888690e-01, -6.69134855e-02],
        [ 2.54202873e-01,  5.77606559e-01, -7.11878464e-02],
        [ 2.52018899e-01,  6.06927633e-01, -6.41074851e-02],
        [ 2.25350142e-01,  5.70919633e-01, -3.77819277e-02],
        [ 2.29911387e-01,  5.38276613e-01, -7.09495023e-02],
        [ 2.36955583e-01,  5.80903351e-01, -6.83231726e-02],
        [ 2.35669553e-01

In [ ]:
np.resize(arr[5], (2 * 21 * 3))

array([ 2.38675401e-01,  6.72467947e-01, -2.83472691e-05,  2.67727405e-01,
        6.40496373e-01, -1.34471003e-02,  2.88694978e-01,  5.92388988e-01,
       -2.29447354e-02,  2.97036827e-01,  5.55968046e-01, -3.53258438e-02,
        2.93872327e-01,  5.27686656e-01, -4.45128083e-02,  2.65941203e-01,
        5.59725642e-01, -1.98728405e-02,  2.73324937e-01,  5.25863707e-01,
       -4.89713028e-02,  2.73967862e-01,  5.66880405e-01, -5.43906763e-02,
        2.70994246e-01,  5.95913172e-01, -5.07622547e-02,  2.46374473e-01,
        5.63132405e-01, -2.71788482e-02,  2.50483215e-01,  5.29888690e-01,
       -6.69134855e-02,  2.54202873e-01,  5.77606559e-01, -7.11878464e-02,
        2.52018899e-01,  6.06927633e-01, -6.41074851e-02,  2.25350142e-01,
        5.70919633e-01, -3.77819277e-02,  2.29911387e-01,  5.38276613e-01,
       -7.09495023e-02,  2.36955583e-01,  5.80903351e-01, -6.83231726e-02,
        2.35669553e-01,  6.07181191e-01, -6.03439547e-02,  2.02982575e-01,
        5.83927035e-01, -

In [ ]:
so = 0
for i in lst:
    so += 1
    np_arr = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/NaN_to_Zero_Arrays/' + i)
    xx.append(np.resize(np_arr, (frame_nums[so - 1], 2 * 21 * 3)))
    yy.append(i.split('_')[1][:-4])
    print(str(so) + ': ' + yy[-1])

1736: bring
1737: brochure
1738: broke
1739: broke
1740: broke
1741: broke
1742: broke
1743: broke
1744: broke
1745: brother
1746: brother
1747: brother
1748: brother
1749: brother
1750: brother
1751: brother
1752: brother
1753: brother
1754: brother
1755: brother
1756: brother
1757: brown
1758: brown
1759: brown


KeyboardInterrupt: ignored

In [ ]:
stacked = np.zeros((17875, 233, 2 * 21 * 3))

In [ ]:
for i in range(17875):
    stacked[i, :frame_nums[i], :] = xx[i]
    print(str(i + 1) + " " + yy[i])

Streaming output truncated to the last 5000 lines.
12876 stay
12877 stay
12878 stay
12879 stay
12880 stay
12881 stay
12882 stay
12883 stay
12884 stay
12885 steal
12886 steal
12887 steal
12888 steal
12889 steal
12890 steal
12891 steal
12892 steal
12893 steal
12894 steel
12895 steel
12896 steel
12897 steel
12898 steel
12899 steel
12900 steel
12901 steel
12902 stepfather
12903 stepfather
12904 stepfather
12905 stepfather
12906 stepfather
12907 stepfather
12908 stepfather
12909 sticky
12910 sticky
12911 still
12912 sting
12913 sting
12914 sting
12915 sting
12916 sting
12917 stink
12918 stink
12919 stink
12920 stink
12921 stink
12922 stink
12923 stink
12924 stink
12925 stink
12926 stir
12927 stir
12928 stir
12929 stir
12930 stir
12931 stir
12932 stitch
12933 stitch
12934 stitch
12935 stitch
12936 stitch
12937 stitch
12938 stomach
12939 stomach
12940 stomach
12941 stomach
12942 stomach
12943 stomach
12944 stomach
12945 stomach
12946 stomach
12947 stop
12948 stop
12949 stop
12950 stop
12951 s

In [ ]:
np.save("/content/drive/MyDrive/EE8101_Deep_Learning/stacked.npy", stacked)

In [ ]:
np.save('/content/drive/MyDrive/EE8101_Deep_Learning/raw_flat.npy', stacked_2)

In [ ]:
stacked = np.load('/content/drive/MyDrive/EE8101_Deep_Learning/stacked.npy')

In [ ]:
stacked_2 = np.zeros((17875, 233, 2 * 21 * 3))

In [ ]:
for i in range(17875):
    stacked_2[i] = np.resize(stacked[i], (233, 2 * 21 * 3))
    print(i + 1)

Streaming output truncated to the last 5000 lines.
12876
12877
12878
12879
12880
12881
12882
12883
12884
12885
12886
12887
12888
12889
12890
12891
12892
12893
12894
12895
12896
12897
12898
12899
12900
12901
12902
12903
12904
12905
12906
12907
12908
12909
12910
12911
12912
12913
12914
12915
12916
12917
12918
12919
12920
12921
12922
12923
12924
12925
12926
12927
12928
12929
12930
12931
12932
12933
12934
12935
12936
12937
12938
12939
12940
12941
12942
12943
12944
12945
12946
12947
12948
12949
12950
12951
12952
12953
12954
12955
12956
12957
12958
12959
12960
12961
12962
12963
12964
12965
12966
12967
12968
12969
12970
12971
12972
12973
12974
12975
12976
12977
12978
12979
12980
12981
12982
12983
12984
12985
12986
12987
12988
12989
12990
12991
12992
12993
12994
12995
12996
12997
12998
12999
13000
13001
13002
13003
13004
13005
13006
13007
13008
13009
13010
13011
13012
13013
13014
13015
13016
13017
13018
13019
13020
13021
13022
13023
13024
13025
13026
13027
13028
13029
13030
13031
13032
13033
1

In [ ]:
falsee = np.isnan(xx[0]).astype(int)

In [ ]:
falsee

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       ...,


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
        

In [ ]:
truee = np.ones(xx[0].shape) - falsee

In [ ]:
truee

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       ...,


       [[[1., 1., 1.],
         [1., 1., 1.],
         [

In [ ]:
np.where(np.isnan(xx[0]), 1, 0)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       ...,


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
        

In [ ]:
testt = tf.convert_to_tensor(xx[0])

In [ ]:
def replace_nan(np_arr):
    lmao = np.isnan(np_arr)
    testt = np_arr
    testt[lmao] = 1
    return testt

In [ ]:
testt

array([[[[ 2.39173457e-01,  6.72451258e-01, -3.21984298e-05],
         [ 2.67859906e-01,  6.41050994e-01, -1.41881099e-02],
         [ 2.88754940e-01,  5.92619777e-01, -2.41917260e-02],
         ...,
         [ 2.04837188e-01,  5.48323452e-01, -7.29365125e-02],
         [ 2.15495735e-01,  5.76515555e-01, -7.40801618e-02],
         [ 2.17770800e-01,  6.00209355e-01, -7.00127631e-02]],

        [[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
         [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
         [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
         ...,
         [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
         [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
         [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00]]],


       [[[ 2.39364684e-01,  6.72565877e-01, -3.05471331e-05],
         [ 2.67917365e-01,  6.41028404e-01, -1.42814433e-02],
         [ 2.88576514e-01,  5.92623889e-01, -2.40088515e-02],
         ...,
         [ 2.04494148e

In [ ]:
testt.shape

(23, 2, 21, 3)

In [ ]:
testt2 = np.reshape(testt, 23 * 2 * 21 * 3)

In [ ]:
xx_2 = []

In [ ]:
xx_2 = []
so = -1
for i in xx:
    so += 1
    xx_2.append(np.reshape(replace_nan(i), (frame_nums[so],2 * 21 * 3)))
    print(len(xx_2))

Streaming output truncated to the last 5000 lines.
12876
12877
12878
12879
12880
12881
12882
12883
12884
12885
12886
12887
12888
12889
12890
12891
12892
12893
12894
12895
12896
12897
12898
12899
12900
12901
12902
12903
12904
12905
12906
12907
12908
12909
12910
12911
12912
12913
12914
12915
12916
12917
12918
12919
12920
12921
12922
12923
12924
12925
12926
12927
12928
12929
12930
12931
12932
12933
12934
12935
12936
12937
12938
12939
12940
12941
12942
12943
12944
12945
12946
12947
12948
12949
12950
12951
12952
12953
12954
12955
12956
12957
12958
12959
12960
12961
12962
12963
12964
12965
12966
12967
12968
12969
12970
12971
12972
12973
12974
12975
12976
12977
12978
12979
12980
12981
12982
12983
12984
12985
12986
12987
12988
12989
12990
12991
12992
12993
12994
12995
12996
12997
12998
12999
13000
13001
13002
13003
13004
13005
13006
13007
13008
13009
13010
13011
13012
13013
13014
13015
13016
13017
13018
13019
13020
13021
13022
13023
13024
13025
13026
13027
13028
13029
13030
13031
13032
13033
1

In [ ]:
len(xx)

17875

In [ ]:
from torch import nn
from torch.nn.utils.rnn import pad_sequence

In [ ]:
xx_pad = pad_sequence(xx_3, batch_first = True, padding_value = 0)

In [ ]:
xx_pad[0]

tensor([[ 2.3917e-01,  6.7245e-01, -3.2198e-05,  ...,  1.0000e+00,
          1.0000e+00,  1.0000e+00],
        [ 2.3936e-01,  6.7257e-01, -3.0547e-05,  ...,  1.0000e+00,
          1.0000e+00,  1.0000e+00],
        [ 2.3945e-01,  6.7234e-01, -3.3011e-05,  ...,  1.0000e+00,
          1.0000e+00,  1.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]], dtype=torch.float64)

In [ ]:
list(xx_2[0])[130]

0.6410284042358398

In [ ]:
xx_3 = []
so = -1
for i in xx_2:
    so += 1
    xx_3.append(torch.from_numpy(xx_2[so]))
    print(str(so) + ' done!')

Streaming output truncated to the last 5000 lines.
12875 done!
12876 done!
12877 done!
12878 done!
12879 done!
12880 done!
12881 done!
12882 done!
12883 done!
12884 done!
12885 done!
12886 done!
12887 done!
12888 done!
12889 done!
12890 done!
12891 done!
12892 done!
12893 done!
12894 done!
12895 done!
12896 done!
12897 done!
12898 done!
12899 done!
12900 done!
12901 done!
12902 done!
12903 done!
12904 done!
12905 done!
12906 done!
12907 done!
12908 done!
12909 done!
12910 done!
12911 done!
12912 done!
12913 done!
12914 done!
12915 done!
12916 done!
12917 done!
12918 done!
12919 done!
12920 done!
12921 done!
12922 done!
12923 done!
12924 done!
12925 done!
12926 done!
12927 done!
12928 done!
12929 done!
12930 done!
12931 done!
12932 done!
12933 done!
12934 done!
12935 done!
12936 done!
12937 done!
12938 done!
12939 done!
12940 done!
12941 done!
12942 done!
12943 done!
12944 done!
12945 done!
12946 done!
12947 done!
12948 done!
12949 done!
12950 done!
12951 done!
12952 done!
12953 done!
1

In [ ]:
np.max(frame_nums)

233